import numpy as np 

a = np.array([1, 2, 3])
print (a)
# more than one dimensions 
b = np.array([[1, 2], [3, 4]]) 
print (b)
c = np.array([1, 2, 3, 4, 5], ndmin=2) 
print (c)
# dtype parameter 
d = np.array([1, 2 + 5j, 3], dtype=np.complex128) 
print (d)
dt = np.dtype(np.int32) 
print (dt)
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')]) 
sd = np.array([('abc', 21, 50), ('xyz', 18, 75), ('Ranjan', 26, 80.43)], dtype=student) 
print (sd)
print(sd.shape)
a = np.array([[1, 2, 3], [4, 5, 6]]) 
print (a.shape)
a = np.array([[1, 2, 3], [4, 5, 6]]) 
a.shape = (3, 2) 
print (a)
a = np.arange(24) 
a.ndim  
# now reshape it 
b = a.reshape(2, 4, 3) 
print (b)
print(sd.itemsize)
print(sd.flags)
ndarray_empty_F = np.empty([3, 2], dtype=np.int, order='F')
print(ndarray_empty_F)
ndarray_empty_C = np.empty([3, 2], dtype=np.int, order='C')
print(ndarray_empty_C)
ndarray_zero = np.zeros([3, 2], dtype=np.int, order='C')
print(ndarray_zero)
ndarray_one = np.ones([3, 2], dtype=np.int, order='C')
print(ndarray_one)
x = [1,2,3] 
a = np.asarray(x, dtype = np.float16) 
print (a)
x = [(1,2,3),(4,5)] 
a = np.asarray(x) 
print (a)
list = range(5) 
it = iter(list)  
# use iterator to create ndarray 
x = np.fromiter(it, dtype = float) 
print (x)
x = np.arange(10,40,2) 
print (x)
x = np.linspace(10,20,5) 
print (x)
x = np.linspace(10,20, 5, endpoint = False) 
print (x)
x = np.linspace(1,2,5, retstep = True) 
print (x)
